### ISSUE TITLE
Print the pattern using loops

### ISSUE THREAD

**Issue by crypticCoder9** [crypticCoder9/Pattern-java#1]
I want to print the pattern as described in the README file.

**Comment by sabthagirivasanv** [comment]
Hi! I have the following list of doubts.
- Your readme is kinda limited in terms of different types of examples. Can you provide more examples?
- How does output look for different values of "n"?

 I am happy to help in this case!!!

**Comment by crypticCoder9** [comment]
> Hi! I have the following list of doubts.
> 
> * Your readme is kinda limited in terms of different types of examples. Can you provide more examples?
> * How does output look for different values of "n"?
> 
> I am happy to help in this case!!!

hi.
This Java program prints a specific pattern of asterisks (*) for rows = 3.
basically we aim to print to hollow triangles without base.
and lets restrict n as 3 only.


thank you.

**Comment by crypticCoder9** [comment]
someone printed the pattern, but still their is some more improvement needed i believe. i would be really happy if you could help me.

**Comment by AlyaanMir** [comment]
If this issue persists, I would be more than willing to examine it and implement the necessary fixes. Please do not hesitate to reach out to me if you require any assistance in resolving this matter.

**Comment by MehekFatima** [comment]
Thank you so much.

**Comment by MehekFatima** [comment]
Thank you so much.

**Comment by crypticCoder9** [comment]
Thank you so much. I'm actually beginner.
